/**
 * Geographic Data Seeder
 * Populates Colombian departments and municipalities (DANE codes)
 *
 * This is a simplified dataset with major departments and municipalities.
 * Full DANE dataset contains 1000+ municipalities.
 */

import { mutation } from "./_generated/server";

export const reseedColombianGeography = mutation({
  args: {},
  handler: async (ctx) => {
    const now = Date.now();

    // Delete all existing geographic data
    const allRecords = await ctx.db
      .query("geographic_locations")
      .withIndex("by_country", (q) => q.eq("country_code", "CO"))
      .collect();

    for (const record of allRecords) {
      await ctx.db.delete(record._id);
    }

    // Then insert fresh data (using the same municipalities array)
    // This will be handled by calling seedColombianGeography afterward
    return {
      message: "Cleared existing geographic data",
      deletedCount: allRecords.length,
    };
  },
});

export const seedColombianGeography = mutation({
  args: {},
  handler: async (ctx) => {
    const now = Date.now();

    // Check if data already exists
    const existingData = await ctx.db
      .query("geographic_locations")
      .withIndex("by_country", (q) => q.eq("country_code", "CO"))
      .first();

    if (existingData) {
      return {
        message: "Geographic data already seeded",
        count: 0,
      };
    }

    // Colombian Departments (DANE Level 1)
    const departments = [
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 1,
        division_1_code: "05",
        division_1_name: "Antioquia",
        timezone: "America/Bogota",
        latitude: 6.2518,
        longitude: -75.5636,
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 1,
        division_1_code: "11",
        division_1_name: "Bogotá D.C.",
        timezone: "America/Bogota",
        latitude: 4.7110,
        longitude: -74.0721,
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 1,
        division_1_code: "76",
        division_1_name: "Valle del Cauca",
        timezone: "America/Bogota",
        latitude: 3.4516,
        longitude: -76.5320,
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 1,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        timezone: "America/Bogota",
        latitude: 5.0214,
        longitude: -74.0575,
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 1,
        division_1_code: "17",
        division_1_name: "Caldas",
        timezone: "America/Bogota",
        latitude: 5.0689,
        longitude: -75.5174,
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 1,
        division_1_code: "63",
        division_1_name: "Quindío",
        timezone: "America/Bogota",
        latitude: 4.4611,
        longitude: -75.6674,
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 1,
        division_1_code: "66",
        division_1_name: "Risaralda",
        timezone: "America/Bogota",
        latitude: 5.3200,
        longitude: -75.9927,
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 1,
        division_1_code: "73",
        division_1_name: "Tolima",
        timezone: "America/Bogota",
        latitude: 4.4389,
        longitude: -75.2322,
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 1,
        division_1_code: "13",
        division_1_name: "Bolívar",
        timezone: "America/Bogota",
        latitude: 10.3910,
        longitude: -75.4794,
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 1,
        division_1_code: "08",
        division_1_name: "Atlántico",
        timezone: "America/Bogota",
        latitude: 10.9639,
        longitude: -74.7964,
        is_active: true,
        created_at: now,
      },
    ];

    // Municipalities (DANE Level 2) - Major cities only for initial seeding
    const municipalities = [
      // Antioquia (Major municipalities and cities)
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "05",
        division_1_name: "Antioquia",
        division_2_code: "05001",
        division_2_name: "Medellín",
        parent_division_1_code: "05",
        latitude: 6.2476,
        longitude: -75.5658,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "05",
        division_1_name: "Antioquia",
        division_2_code: "05002",
        division_2_name: "Abejorral",
        parent_division_1_code: "05",
        latitude: 5.8447,
        longitude: -75.1697,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "05",
        division_1_name: "Antioquia",
        division_2_code: "05004",
        division_2_name: "Abriaquí",
        parent_division_1_code: "05",
        latitude: 6.4833,
        longitude: -76.1500,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "05",
        division_1_name: "Antioquia",
        division_2_code: "05021",
        division_2_name: "Alejandría",
        parent_division_1_code: "05",
        latitude: 6.1333,
        longitude: -75.1833,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "05",
        division_1_name: "Antioquia",
        division_2_code: "05030",
        division_2_name: "Amalfi",
        parent_division_1_code: "05",
        latitude: 6.4500,
        longitude: -75.1000,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "05",
        division_1_name: "Antioquia",
        division_2_code: "05088",
        division_2_name: "Bello",
        parent_division_1_code: "05",
        latitude: 6.3377,
        longitude: -75.5603,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "05",
        division_1_name: "Antioquia",
        division_2_code: "05106",
        division_2_name: "Caracolí",
        parent_division_1_code: "05",
        latitude: 5.5833,
        longitude: -74.9833,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "05",
        division_1_name: "Antioquia",
        division_2_code: "05125",
        division_2_name: "Copacabana",
        parent_division_1_code: "05",
        latitude: 6.3950,
        longitude: -75.5169,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "05",
        division_1_name: "Antioquia",
        division_2_code: "05129",
        division_2_name: "Córdoba",
        parent_division_1_code: "05",
        latitude: 6.8083,
        longitude: -75.8306,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "05",
        division_1_name: "Antioquia",
        division_2_code: "05217",
        division_2_name: "Envigado",
        parent_division_1_code: "05",
        latitude: 6.1667,
        longitude: -75.5833,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "05",
        division_1_name: "Antioquia",
        division_2_code: "05235",
        division_2_name: "Girardota",
        parent_division_1_code: "05",
        latitude: 6.4758,
        longitude: -75.4869,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "05",
        division_1_name: "Antioquia",
        division_2_code: "05240",
        division_2_name: "Gómez Plata",
        parent_division_1_code: "05",
        latitude: 6.7667,
        longitude: -75.2167,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "05",
        division_1_name: "Antioquia",
        division_2_code: "05308",
        division_2_name: "Guarne",
        parent_division_1_code: "05",
        latitude: 6.2744,
        longitude: -75.4414,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "05",
        division_1_name: "Antioquia",
        division_2_code: "05318",
        division_2_name: "Guatapé",
        parent_division_1_code: "05",
        latitude: 6.2297,
        longitude: -75.1728,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "05",
        division_1_name: "Antioquia",
        division_2_code: "05361",
        division_2_name: "Itagüí",
        parent_division_1_code: "05",
        latitude: 6.1667,
        longitude: -75.6500,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "05",
        division_1_name: "Antioquia",
        division_2_code: "05380",
        division_2_name: "La Ceja",
        parent_division_1_code: "05",
        latitude: 6.0500,
        longitude: -75.3833,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "05",
        division_1_name: "Antioquia",
        division_2_code: "05384",
        division_2_name: "La Pintada",
        parent_division_1_code: "05",
        latitude: 5.6500,
        longitude: -75.4667,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "05",
        division_1_name: "Antioquia",
        division_2_code: "05393",
        division_2_name: "La Unión",
        parent_division_1_code: "05",
        latitude: 5.9667,
        longitude: -75.5333,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "05",
        division_1_name: "Antioquia",
        division_2_code: "05411",
        division_2_name: "Liborina",
        parent_division_1_code: "05",
        latitude: 6.6500,
        longitude: -75.6333,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "05",
        division_1_name: "Antioquia",
        division_2_code: "05440",
        division_2_name: "Marinilla",
        parent_division_1_code: "05",
        latitude: 6.1500,
        longitude: -75.4167,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "05",
        division_1_name: "Antioquia",
        division_2_code: "05467",
        division_2_name: "Montebello",
        parent_division_1_code: "05",
        latitude: 6.2500,
        longitude: -75.7833,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "05",
        division_1_name: "Antioquia",
        division_2_code: "05479",
        division_2_name: "Mutatá",
        parent_division_1_code: "05",
        latitude: 7.3667,
        longitude: -76.4333,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "05",
        division_1_name: "Antioquia",
        division_2_code: "05493",
        division_2_name: "Nariño",
        parent_division_1_code: "05",
        latitude: 5.9667,
        longitude: -75.6833,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "05",
        division_1_name: "Antioquia",
        division_2_code: "05501",
        division_2_name: "Necoclí",
        parent_division_1_code: "05",
        latitude: 8.4167,
        longitude: -76.7833,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "05",
        division_1_name: "Antioquia",
        division_2_code: "05541",
        division_2_name: "Peñol",
        parent_division_1_code: "05",
        latitude: 6.1333,
        longitude: -75.2167,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "05",
        division_1_name: "Antioquia",
        division_2_code: "05614",
        division_2_name: "Rionegro",
        parent_division_1_code: "05",
        latitude: 6.1436,
        longitude: -75.3778,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "05",
        division_1_name: "Antioquia",
        division_2_code: "05631",
        division_2_name: "Sabaneta",
        parent_division_1_code: "05",
        latitude: 6.1333,
        longitude: -75.5833,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "05",
        division_1_name: "Antioquia",
        division_2_code: "05645",
        division_2_name: "Salgar",
        parent_division_1_code: "05",
        latitude: 6.0333,
        longitude: -75.6833,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "05",
        division_1_name: "Antioquia",
        division_2_code: "05665",
        division_2_name: "Santa Rosa de Osos",
        parent_division_1_code: "05",
        latitude: 7.1333,
        longitude: -75.5333,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "05",
        division_1_name: "Antioquia",
        division_2_code: "05686",
        division_2_name: "Santo Domingo",
        parent_division_1_code: "05",
        latitude: 6.0167,
        longitude: -75.8167,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "05",
        division_1_name: "Antioquia",
        division_2_code: "05698",
        division_2_name: "Sonson",
        parent_division_1_code: "05",
        latitude: 5.6167,
        longitude: -75.2333,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "05",
        division_1_name: "Antioquia",
        division_2_code: "05734",
        division_2_name: "Támesis",
        parent_division_1_code: "05",
        latitude: 5.5667,
        longitude: -75.8333,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "05",
        division_1_name: "Antioquia",
        division_2_code: "05738",
        division_2_name: "Tarso",
        parent_division_1_code: "05",
        latitude: 6.1167,
        longitude: -75.9167,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "05",
        division_1_name: "Antioquia",
        division_2_code: "05800",
        division_2_name: "Titiribi",
        parent_division_1_code: "05",
        latitude: 5.8167,
        longitude: -75.7500,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "05",
        division_1_name: "Antioquia",
        division_2_code: "05809",
        division_2_name: "Tolú",
        parent_division_1_code: "05",
        latitude: 6.3000,
        longitude: -75.6667,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "05",
        division_1_name: "Antioquia",
        division_2_code: "05835",
        division_2_name: "Turbo",
        parent_division_1_code: "05",
        latitude: 8.0833,
        longitude: -76.7333,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "05",
        division_1_name: "Antioquia",
        division_2_code: "05858",
        division_2_name: "Uramita",
        parent_division_1_code: "05",
        latitude: 7.1167,
        longitude: -76.1333,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "05",
        division_1_name: "Antioquia",
        division_2_code: "05861",
        division_2_name: "Urrao",
        parent_division_1_code: "05",
        latitude: 6.1000,
        longitude: -76.1333,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "05",
        division_1_name: "Antioquia",
        division_2_code: "05873",
        division_2_name: "Valdivia",
        parent_division_1_code: "05",
        latitude: 6.9333,
        longitude: -75.5167,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "05",
        division_1_name: "Antioquia",
        division_2_code: "05876",
        division_2_name: "Vegachí",
        parent_division_1_code: "05",
        latitude: 6.9167,
        longitude: -75.3833,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "05",
        division_1_name: "Antioquia",
        division_2_code: "05887",
        division_2_name: "Venecia",
        parent_division_1_code: "05",
        latitude: 5.7333,
        longitude: -75.5500,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "05",
        division_1_name: "Antioquia",
        division_2_code: "05893",
        division_2_name: "Vigía del Fuerte",
        parent_division_1_code: "05",
        latitude: 7.6000,
        longitude: -76.6500,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "05",
        division_1_name: "Antioquia",
        division_2_code: "05895",
        division_2_name: "Yalí",
        parent_division_1_code: "05",
        latitude: 6.9500,
        longitude: -75.0833,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "05",
        division_1_name: "Antioquia",
        division_2_code: "05898",
        division_2_name: "Yarumal",
        parent_division_1_code: "05",
        latitude: 6.7667,
        longitude: -75.4000,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "05",
        division_1_name: "Antioquia",
        division_2_code: "05910",
        division_2_name: "Yolombó",
        parent_division_1_code: "05",
        latitude: 6.6167,
        longitude: -75.1000,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      // Bogotá D.C.
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "11",
        division_1_name: "Bogotá D.C.",
        division_2_code: "11001",
        division_2_name: "Bogotá D.C.",
        parent_division_1_code: "11",
        latitude: 4.7110,
        longitude: -74.0721,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      // Valle del Cauca
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "76",
        division_1_name: "Valle del Cauca",
        division_2_code: "76001",
        division_2_name: "Cali",
        parent_division_1_code: "76",
        latitude: 3.4516,
        longitude: -76.5320,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "76",
        division_1_name: "Valle del Cauca",
        division_2_code: "76111",
        division_2_name: "Buenaventura",
        parent_division_1_code: "76",
        latitude: 3.8801,
        longitude: -77.0310,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      // Cundinamarca (Major municipalities and cities)
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25001",
        division_2_name: "Agua de Dios",
        parent_division_1_code: "25",
        latitude: 4.3764,
        longitude: -74.6703,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25019",
        division_2_name: "Albán",
        parent_division_1_code: "25",
        latitude: 4.9500,
        longitude: -74.2167,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25035",
        division_2_name: "Anapoima",
        parent_division_1_code: "25",
        latitude: 4.6833,
        longitude: -74.2417,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25040",
        division_2_name: "Anolaima",
        parent_division_1_code: "25",
        latitude: 4.8889,
        longitude: -74.3778,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25053",
        division_2_name: "Apulo",
        parent_division_1_code: "25",
        latitude: 4.8417,
        longitude: -74.2917,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25086",
        division_2_name: "Arbeláez",
        parent_division_1_code: "25",
        latitude: 4.3500,
        longitude: -74.4333,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25095",
        division_2_name: "Arroyozuelo",
        parent_division_1_code: "25",
        latitude: 4.2500,
        longitude: -74.1833,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25099",
        division_2_name: "Artesía",
        parent_division_1_code: "25",
        latitude: 4.5333,
        longitude: -73.8000,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25175",
        division_2_name: "Chía",
        parent_division_1_code: "25",
        latitude: 4.8619,
        longitude: -74.0517,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25178",
        division_2_name: "Choachí",
        parent_division_1_code: "25",
        latitude: 4.7833,
        longitude: -73.9333,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25181",
        division_2_name: "Chocontá",
        parent_division_1_code: "25",
        latitude: 5.3333,
        longitude: -73.6833,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25207",
        division_2_name: "Cogua",
        parent_division_1_code: "25",
        latitude: 5.1333,
        longitude: -74.0000,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25245",
        division_2_name: "Cota",
        parent_division_1_code: "25",
        latitude: 4.9167,
        longitude: -74.1333,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25258",
        division_2_name: "Cucunubá",
        parent_division_1_code: "25",
        latitude: 5.2833,
        longitude: -73.5333,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25268",
        division_2_name: "Curití",
        parent_division_1_code: "25",
        latitude: 5.8000,
        longitude: -73.5333,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25275",
        division_2_name: "Duitama",
        parent_division_1_code: "25",
        latitude: 5.2833,
        longitude: -73.0500,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25297",
        division_2_name: "El Peñol",
        parent_division_1_code: "25",
        latitude: 4.4167,
        longitude: -74.3667,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25313",
        division_2_name: "El Rosal",
        parent_division_1_code: "25",
        latitude: 4.9000,
        longitude: -74.2000,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25318",
        division_2_name: "Enrique Peña Nieto",
        parent_division_1_code: "25",
        latitude: 4.7500,
        longitude: -74.0833,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25325",
        division_2_name: "Espandé",
        parent_division_1_code: "25",
        latitude: 4.3000,
        longitude: -74.0000,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25360",
        division_2_name: "Funza",
        parent_division_1_code: "25",
        latitude: 4.8667,
        longitude: -74.2667,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25368",
        division_2_name: "Fusagasugá",
        parent_division_1_code: "25",
        latitude: 4.1379,
        longitude: -74.3721,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25377",
        division_2_name: "Gachalá",
        parent_division_1_code: "25",
        latitude: 5.0667,
        longitude: -73.7333,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25380",
        division_2_name: "Gachancipá",
        parent_division_1_code: "25",
        latitude: 5.1500,
        longitude: -73.8500,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25389",
        division_2_name: "Gacheta",
        parent_division_1_code: "25",
        latitude: 5.4333,
        longitude: -73.5667,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25403",
        division_2_name: "Guacheta",
        parent_division_1_code: "25",
        latitude: 5.6000,
        longitude: -73.3500,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25406",
        division_2_name: "Guaduas",
        parent_division_1_code: "25",
        latitude: 5.1789,
        longitude: -74.5956,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25418",
        division_2_name: "Guasca",
        parent_division_1_code: "25",
        latitude: 5.0333,
        longitude: -73.8500,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25421",
        division_2_name: "Guataquí",
        parent_division_1_code: "25",
        latitude: 5.0522,
        longitude: -74.3819,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25430",
        division_2_name: "Guaviarê",
        parent_division_1_code: "25",
        latitude: 2.7500,
        longitude: -72.6333,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25436",
        division_2_name: "Guerrero",
        parent_division_1_code: "25",
        latitude: 4.5167,
        longitude: -74.1167,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25439",
        division_2_name: "Gutiérrez",
        parent_division_1_code: "25",
        latitude: 4.3167,
        longitude: -73.9500,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25473",
        division_2_name: "Ituango",
        parent_division_1_code: "25",
        latitude: 4.8500,
        longitude: -73.9667,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25518",
        division_2_name: "La Calera",
        parent_division_1_code: "25",
        latitude: 4.9333,
        longitude: -74.0333,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25522",
        division_2_name: "La Mesa",
        parent_division_1_code: "25",
        latitude: 4.7667,
        longitude: -74.3667,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25531",
        division_2_name: "La Palma",
        parent_division_1_code: "25",
        latitude: 5.1000,
        longitude: -74.5333,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25540",
        division_2_name: "La Peña",
        parent_division_1_code: "25",
        latitude: 4.5333,
        longitude: -74.1333,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25546",
        division_2_name: "La Vega",
        parent_division_1_code: "25",
        latitude: 5.2333,
        longitude: -74.3500,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25555",
        division_2_name: "Lenguazaque",
        parent_division_1_code: "25",
        latitude: 5.4000,
        longitude: -73.7000,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25564",
        division_2_name: "Macheta",
        parent_division_1_code: "25",
        latitude: 5.3667,
        longitude: -73.5167,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25573",
        division_2_name: "Madrid",
        parent_division_1_code: "25",
        latitude: 4.8500,
        longitude: -74.2167,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25588",
        division_2_name: "Manta",
        parent_division_1_code: "25",
        latitude: 4.4333,
        longitude: -74.1667,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25592",
        division_2_name: "Medina",
        parent_division_1_code: "25",
        latitude: 4.5500,
        longitude: -73.8667,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25599",
        division_2_name: "Mesetas",
        parent_division_1_code: "25",
        latitude: 3.8000,
        longitude: -73.2000,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25606",
        division_2_name: "Micará",
        parent_division_1_code: "25",
        latitude: 4.2500,
        longitude: -74.0500,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25616",
        division_2_name: "Moca",
        parent_division_1_code: "25",
        latitude: 4.3667,
        longitude: -74.0333,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25622",
        division_2_name: "Monsalve",
        parent_division_1_code: "25",
        latitude: 5.0000,
        longitude: -73.8667,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25639",
        division_2_name: "Muezo",
        parent_division_1_code: "25",
        latitude: 5.6667,
        longitude: -73.8833,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25642",
        division_2_name: "Naranjal",
        parent_division_1_code: "25",
        latitude: 5.8667,
        longitude: -73.8500,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25648",
        division_2_name: "Nario",
        parent_division_1_code: "25",
        latitude: 4.7500,
        longitude: -74.0333,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25651",
        division_2_name: "Nemocón",
        parent_division_1_code: "25",
        latitude: 5.2667,
        longitude: -73.7500,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25655",
        division_2_name: "Nile",
        parent_division_1_code: "25",
        latitude: 5.7500,
        longitude: -73.0000,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25658",
        division_2_name: "Nimaima",
        parent_division_1_code: "25",
        latitude: 5.2333,
        longitude: -74.5667,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25662",
        division_2_name: "Norabuena",
        parent_division_1_code: "25",
        latitude: 5.3667,
        longitude: -74.4167,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25668",
        division_2_name: "Noquichoque",
        parent_division_1_code: "25",
        latitude: 5.4500,
        longitude: -73.8500,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25678",
        division_2_name: "Ospina Pérez",
        parent_division_1_code: "25",
        latitude: 4.8000,
        longitude: -74.1833,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25683",
        division_2_name: "Otanche",
        parent_division_1_code: "25",
        latitude: 5.5667,
        longitude: -74.4333,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25686",
        division_2_name: "Pacho",
        parent_division_1_code: "25",
        latitude: 5.1333,
        longitude: -74.2833,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25690",
        division_2_name: "Paime",
        parent_division_1_code: "25",
        latitude: 5.0833,
        longitude: -74.3833,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25693",
        division_2_name: "Palermo",
        parent_division_1_code: "25",
        latitude: 4.9500,
        longitude: -74.3333,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25696",
        division_2_name: "Palos Blancos",
        parent_division_1_code: "25",
        latitude: 5.4833,
        longitude: -73.9000,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25699",
        division_2_name: "Paracuellos",
        parent_division_1_code: "25",
        latitude: 5.1667,
        longitude: -73.6667,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25702",
        division_2_name: "Paratebueno",
        parent_division_1_code: "25",
        latitude: 4.8000,
        longitude: -73.7167,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25707",
        division_2_name: "Parque Nacional Natural",
        parent_division_1_code: "25",
        latitude: 4.7500,
        longitude: -74.0000,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25710",
        division_2_name: "Pasca",
        parent_division_1_code: "25",
        latitude: 4.5500,
        longitude: -74.2500,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25715",
        division_2_name: "Pereira",
        parent_division_1_code: "25",
        latitude: 5.0333,
        longitude: -73.5167,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25721",
        division_2_name: "Peñalisa",
        parent_division_1_code: "25",
        latitude: 5.5167,
        longitude: -73.6833,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25729",
        division_2_name: "Pie de Orilla",
        parent_division_1_code: "25",
        latitude: 5.6500,
        longitude: -73.4833,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25735",
        division_2_name: "Pijao",
        parent_division_1_code: "25",
        latitude: 4.8667,
        longitude: -73.5333,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25740",
        division_2_name: "Pinto",
        parent_division_1_code: "25",
        latitude: 4.3000,
        longitude: -74.3000,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25743",
        division_2_name: "Piracicaba",
        parent_division_1_code: "25",
        latitude: 4.9333,
        longitude: -73.6500,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25750",
        division_2_name: "Plegamazos",
        parent_division_1_code: "25",
        latitude: 4.8333,
        longitude: -74.4167,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25756",
        division_2_name: "Policarpa",
        parent_division_1_code: "25",
        latitude: 4.1167,
        longitude: -74.1833,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25758",
        division_2_name: "Puente Nacional",
        parent_division_1_code: "25",
        latitude: 5.8333,
        longitude: -73.2333,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25760",
        division_2_name: "Puigwila",
        parent_division_1_code: "25",
        latitude: 4.4167,
        longitude: -74.2500,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25764",
        division_2_name: "Quero",
        parent_division_1_code: "25",
        latitude: 4.5667,
        longitude: -73.9000,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25767",
        division_2_name: "Quetame",
        parent_division_1_code: "25",
        latitude: 4.6500,
        longitude: -73.8333,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25775",
        division_2_name: "Radiocha",
        parent_division_1_code: "25",
        latitude: 5.2167,
        longitude: -73.7333,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25778",
        division_2_name: "Ramiriquí",
        parent_division_1_code: "25",
        latitude: 5.5833,
        longitude: -73.2500,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25781",
        division_2_name: "Rasgón",
        parent_division_1_code: "25",
        latitude: 4.3500,
        longitude: -73.8833,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25785",
        division_2_name: "Raya",
        parent_division_1_code: "25",
        latitude: 4.6167,
        longitude: -74.0833,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25793",
        division_2_name: "Rofaguaya",
        parent_division_1_code: "25",
        latitude: 4.7333,
        longitude: -73.6667,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25798",
        division_2_name: "Roncesvalle",
        parent_division_1_code: "25",
        latitude: 5.2667,
        longitude: -74.3833,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25800",
        division_2_name: "Rosario",
        parent_division_1_code: "25",
        latitude: 4.9833,
        longitude: -74.4333,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25806",
        division_2_name: "Sabanaláiaga",
        parent_division_1_code: "25",
        latitude: 4.5833,
        longitude: -74.0167,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25809",
        division_2_name: "Sabanarica",
        parent_division_1_code: "25",
        latitude: 4.4833,
        longitude: -74.0833,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25815",
        division_2_name: "Saboya",
        parent_division_1_code: "25",
        latitude: 5.5000,
        longitude: -73.1667,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25820",
        division_2_name: "Sacaboy",
        parent_division_1_code: "25",
        latitude: 5.1833,
        longitude: -74.4667,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25824",
        division_2_name: "Sáchica",
        parent_division_1_code: "25",
        latitude: 5.2500,
        longitude: -73.1333,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25827",
        division_2_name: "Sacradá",
        parent_division_1_code: "25",
        latitude: 5.0333,
        longitude: -73.9167,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25835",
        division_2_name: "Salazar",
        parent_division_1_code: "25",
        latitude: 5.6500,
        longitude: -73.2667,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25839",
        division_2_name: "Salcajá",
        parent_division_1_code: "25",
        latitude: 5.3333,
        longitude: -74.2333,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25845",
        division_2_name: "Samacá",
        parent_division_1_code: "25",
        latitude: 5.5333,
        longitude: -73.2500,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25851",
        division_2_name: "Samandí",
        parent_division_1_code: "25",
        latitude: 4.5000,
        longitude: -73.7000,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25854",
        division_2_name: "Santagueda",
        parent_division_1_code: "25",
        latitude: 5.2167,
        longitude: -75.3667,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25859",
        division_2_name: "Santander",
        parent_division_1_code: "25",
        latitude: 5.4500,
        longitude: -73.0500,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25862",
        division_2_name: "Santuario",
        parent_division_1_code: "25",
        latitude: 4.4667,
        longitude: -74.4167,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25867",
        division_2_name: "Sasaima",
        parent_division_1_code: "25",
        latitude: 5.0333,
        longitude: -74.5333,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25873",
        division_2_name: "Sesquile",
        parent_division_1_code: "25",
        latitude: 5.2000,
        longitude: -73.8667,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25876",
        division_2_name: "Sibaté",
        parent_division_1_code: "25",
        latitude: 4.7667,
        longitude: -74.2000,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25883",
        division_2_name: "Soatá",
        parent_division_1_code: "25",
        latitude: 6.0000,
        longitude: -73.0167,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25885",
        division_2_name: "Socotá",
        parent_division_1_code: "25",
        latitude: 6.0500,
        longitude: -72.9500,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      // Caldas
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "17",
        division_1_name: "Caldas",
        division_2_code: "17001",
        division_2_name: "Manizales",
        parent_division_1_code: "17",
        latitude: 5.0689,
        longitude: -75.5174,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      // Quindío
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "63",
        division_1_name: "Quindío",
        division_2_code: "63001",
        division_2_name: "Armenia",
        parent_division_1_code: "63",
        latitude: 4.5339,
        longitude: -75.6811,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      // Risaralda
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "66",
        division_1_name: "Risaralda",
        division_2_code: "66001",
        division_2_name: "Pereira",
        parent_division_1_code: "66",
        latitude: 4.8133,
        longitude: -75.6961,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      // Tolima
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "73",
        division_1_name: "Tolima",
        division_2_code: "73001",
        division_2_name: "Ibagué",
        parent_division_1_code: "73",
        latitude: 4.4389,
        longitude: -75.2322,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      // Bolívar
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "13",
        division_1_name: "Bolívar",
        division_2_code: "13001",
        division_2_name: "Cartagena",
        parent_division_1_code: "13",
        latitude: 10.3910,
        longitude: -75.4794,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      // Atlántico
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "08",
        division_1_name: "Atlántico",
        division_2_code: "08001",
        division_2_name: "Barranquilla",
        parent_division_1_code: "08",
        latitude: 10.9685,
        longitude: -74.7813,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
    ];

    // Insert all departments
    for (const dept of departments) {
      await ctx.db.insert("geographic_locations", dept);
    }

    // Insert all municipalities
    for (const muni of municipalities) {
      await ctx.db.insert("geographic_locations", muni);
    }

    return {
      message: "Geographic data seeded successfully",
      departments: departments.length,
      municipalities: municipalities.length,
      total: departments.length + municipalities.length,
    };
  },
});
