/**
 * Geographic Data Seeder for Colombia
 * Populates all 33 departments and municipalities using DANE codes
 *
 * Data structure:
 * - 33 Departments (Division 1)
 * - 1100+ Municipalities (Division 2) - Complete for major departments
 */

import { mutation } from "./_generated/server";

export const reseedColombianGeography = mutation({
  args: {},
  handler: async (ctx) => {
    const now = Date.now();

    // Delete all existing geographic data
    const allRecords = await ctx.db
      .query("geographic_locations")
      .withIndex("by_country", (q) => q.eq("country_code", "CO"))
      .collect();

    for (const record of allRecords) {
      await ctx.db.delete(record._id);
    }

    return {
      message: "Cleared existing geographic data",
      deletedCount: allRecords.length,
    };
  },
});

export const seedColombianGeography = mutation({
  args: {},
  handler: async (ctx) => {
    const now = Date.now();

    // Check if data already exists
    const existingData = await ctx.db
      .query("geographic_locations")
      .withIndex("by_country", (q) => q.eq("country_code", "CO"))
      .first();

    if (existingData) {
      return {
        message: "Geographic data already seeded",
        count: 0,
      };
    }

    // ========================================
    // ALL 33 COLOMBIAN DEPARTMENTS (DANE Level 1)
    // ========================================
    const departments = [
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 1,
        division_1_code: "05",
        division_1_name: "Antioquia",
        timezone: "America/Bogota",
        latitude: 6.2518,
        longitude: -75.5636,
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 1,
        division_1_code: "08",
        division_1_name: "Atlántico",
        timezone: "America/Bogota",
        latitude: 10.9639,
        longitude: -74.7964,
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 1,
        division_1_code: "11",
        division_1_name: "Bogotá D.C.",
        timezone: "America/Bogota",
        latitude: 4.7110,
        longitude: -74.0721,
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 1,
        division_1_code: "13",
        division_1_name: "Bolívar",
        timezone: "America/Bogota",
        latitude: 10.3910,
        longitude: -75.4794,
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 1,
        division_1_code: "15",
        division_1_name: "Boyacá",
        timezone: "America/Bogota",
        latitude: 5.4545,
        longitude: -73.3625,
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 1,
        division_1_code: "17",
        division_1_name: "Caldas",
        timezone: "America/Bogota",
        latitude: 5.0689,
        longitude: -75.5174,
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 1,
        division_1_code: "18",
        division_1_name: "Caquetá",
        timezone: "America/Bogota",
        latitude: 1.6145,
        longitude: -75.6062,
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 1,
        division_1_code: "19",
        division_1_name: "Cauca",
        timezone: "America/Bogota",
        latitude: 2.4448,
        longitude: -76.6147,
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 1,
        division_1_code: "20",
        division_1_name: "Cesar",
        timezone: "America/Bogota",
        latitude: 9.3373,
        longitude: -73.6536,
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 1,
        division_1_code: "23",
        division_1_name: "Córdoba",
        timezone: "America/Bogota",
        latitude: 8.7479,
        longitude: -75.8814,
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 1,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        timezone: "America/Bogota",
        latitude: 5.0214,
        longitude: -74.0575,
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 1,
        division_1_code: "27",
        division_1_name: "Chocó",
        timezone: "America/Bogota",
        latitude: 5.6978,
        longitude: -76.6611,
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 1,
        division_1_code: "41",
        division_1_name: "Huila",
        timezone: "America/Bogota",
        latitude: 2.5359,
        longitude: -75.5277,
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 1,
        division_1_code: "44",
        division_1_name: "La Guajira",
        timezone: "America/Bogota",
        latitude: 11.5447,
        longitude: -72.9072,
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 1,
        division_1_code: "47",
        division_1_name: "Magdalena",
        timezone: "America/Bogota",
        latitude: 10.4113,
        longitude: -74.4054,
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 1,
        division_1_code: "50",
        division_1_name: "Meta",
        timezone: "America/Bogota",
        latitude: 3.3272,
        longitude: -73.2847,
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 1,
        division_1_code: "52",
        division_1_name: "Nariño",
        timezone: "America/Bogota",
        latitude: 1.2136,
        longitude: -77.2811,
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 1,
        division_1_code: "54",
        division_1_name: "Norte de Santander",
        timezone: "America/Bogota",
        latitude: 7.9465,
        longitude: -72.8988,
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 1,
        division_1_code: "63",
        division_1_name: "Quindío",
        timezone: "America/Bogota",
        latitude: 4.4611,
        longitude: -75.6674,
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 1,
        division_1_code: "66",
        division_1_name: "Risaralda",
        timezone: "America/Bogota",
        latitude: 5.3200,
        longitude: -75.9927,
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 1,
        division_1_code: "68",
        division_1_name: "Santander",
        timezone: "America/Bogota",
        latitude: 7.1254,
        longitude: -73.1198,
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 1,
        division_1_code: "70",
        division_1_name: "Sucre",
        timezone: "America/Bogota",
        latitude: 9.1547,
        longitude: -75.3472,
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 1,
        division_1_code: "73",
        division_1_name: "Tolima",
        timezone: "America/Bogota",
        latitude: 4.4389,
        longitude: -75.2322,
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 1,
        division_1_code: "76",
        division_1_name: "Valle del Cauca",
        timezone: "America/Bogota",
        latitude: 3.4516,
        longitude: -76.5320,
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 1,
        division_1_code: "81",
        division_1_name: "Arauca",
        timezone: "America/Bogota",
        latitude: 7.0902,
        longitude: -70.7617,
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 1,
        division_1_code: "85",
        division_1_name: "Casanare",
        timezone: "America/Bogota",
        latitude: 5.7589,
        longitude: -71.5724,
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 1,
        division_1_code: "86",
        division_1_name: "Putumayo",
        timezone: "America/Bogota",
        latitude: 0.4945,
        longitude: -75.5236,
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 1,
        division_1_code: "88",
        division_1_name: "Archipiélago de San Andrés, Providencia y Santa Catalina",
        timezone: "America/Bogota",
        latitude: 12.5847,
        longitude: -81.7006,
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 1,
        division_1_code: "91",
        division_1_name: "Amazonas",
        timezone: "America/Bogota",
        latitude: -1.4442,
        longitude: -71.6388,
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 1,
        division_1_code: "94",
        division_1_name: "Guainía",
        timezone: "America/Bogota",
        latitude: 2.5833,
        longitude: -68.5167,
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 1,
        division_1_code: "95",
        division_1_name: "Guaviare",
        timezone: "America/Bogota",
        latitude: 2.0833,
        longitude: -72.6389,
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 1,
        division_1_code: "97",
        division_1_name: "Vaupés",
        timezone: "America/Bogota",
        latitude: 0.8554,
        longitude: -70.8138,
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 1,
        division_1_code: "99",
        division_1_name: "Vichada",
        timezone: "America/Bogota",
        latitude: 4.4231,
        longitude: -69.2894,
        is_active: true,
        created_at: now,
      },
    ];

    // ========================================
    // MUNICIPALITIES - COMPLETE FOR MAJOR DEPARTMENTS
    // ========================================
    const municipalities = [
      // BOGOTÁ D.C. (1 municipio)
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "11",
        division_1_name: "Bogotá D.C.",
        division_2_code: "11001",
        division_2_name: "Bogotá D.C.",
        parent_division_1_code: "11",
        latitude: 4.7110,
        longitude: -74.0721,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },

      // ANTIOQUIA - TODOS LOS 125 MUNICIPIOS
      // Capital y área metropolitana
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "05",
        division_1_name: "Antioquia",
        division_2_code: "05001",
        division_2_name: "Medellín",
        parent_division_1_code: "05",
        latitude: 6.2476,
        longitude: -75.5658,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "05",
        division_1_name: "Antioquia",
        division_2_code: "05088",
        division_2_name: "Bello",
        parent_division_1_code: "05",
        latitude: 6.3377,
        longitude: -75.5603,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "05",
        division_1_name: "Antioquia",
        division_2_code: "05360",
        division_2_name: "Itagüí",
        parent_division_1_code: "05",
        latitude: 6.1849,
        longitude: -75.5994,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "05",
        division_1_name: "Antioquia",
        division_2_code: "05217",
        division_2_name: "Envigado",
        parent_division_1_code: "05",
        latitude: 6.1667,
        longitude: -75.5833,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "05",
        division_1_name: "Antioquia",
        division_2_code: "05631",
        division_2_name: "Sabaneta",
        parent_division_1_code: "05",
        latitude: 6.1512,
        longitude: -75.6169,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "05",
        division_1_name: "Antioquia",
        division_2_code: "05380",
        division_2_name: "La Estrella",
        parent_division_1_code: "05",
        latitude: 6.1583,
        longitude: -75.6417,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "05",
        division_1_name: "Antioquia",
        division_2_code: "05125",
        division_2_name: "Copacabana",
        parent_division_1_code: "05",
        latitude: 6.3486,
        longitude: -75.5078,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "05",
        division_1_name: "Antioquia",
        division_2_code: "05237",
        division_2_name: "Girardota",
        parent_division_1_code: "05",
        latitude: 6.3758,
        longitude: -75.4469,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "05",
        division_1_name: "Antioquia",
        division_2_code: "05079",
        division_2_name: "Barbosa",
        parent_division_1_code: "05",
        latitude: 6.4389,
        longitude: -75.3308,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "05",
        division_1_name: "Antioquia",
        division_2_code: "05129",
        division_2_name: "Caldas",
        parent_division_1_code: "05",
        latitude: 6.0917,
        longitude: -75.6333,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      // Oriente Antioqueño
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "05",
        division_1_name: "Antioquia",
        division_2_code: "05615",
        division_2_name: "Rionegro",
        parent_division_1_code: "05",
        latitude: 6.1436,
        longitude: -75.3758,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "05",
        division_1_name: "Antioquia",
        division_2_code: "05308",
        division_2_name: "Guarne",
        parent_division_1_code: "05",
        latitude: 6.2744,
        longitude: -75.4414,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "05",
        division_1_name: "Antioquia",
        division_2_code: "05440",
        division_2_name: "Marinilla",
        parent_division_1_code: "05",
        latitude: 6.1722,
        longitude: -75.3358,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "05",
        division_1_name: "Antioquia",
        division_2_code: "05101",
        division_2_name: "El Carmen de Viboral",
        parent_division_1_code: "05",
        latitude: 6.0806,
        longitude: -75.3361,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "05",
        division_1_name: "Antioquia",
        division_2_code: "05647",
        division_2_name: "San Vicente",
        parent_division_1_code: "05",
        latitude: 6.2889,
        longitude: -75.3303,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "05",
        division_1_name: "Antioquia",
        division_2_code: "05697",
        division_2_name: "Sonsón",
        parent_division_1_code: "05",
        latitude: 5.7083,
        longitude: -75.3111,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "05",
        division_1_name: "Antioquia",
        division_2_code: "05318",
        division_2_name: "Guatapé",
        parent_division_1_code: "05",
        latitude: 6.2297,
        longitude: -75.1728,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "05",
        division_1_name: "Antioquia",
        division_2_code: "05541",
        division_2_name: "El Peñol",
        parent_division_1_code: "05",
        latitude: 6.2167,
        longitude: -75.2333,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "05",
        division_1_name: "Antioquia",
        division_2_code: "05148",
        division_2_name: "La Ceja",
        parent_division_1_code: "05",
        latitude: 6.0292,
        longitude: -75.4272,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "05",
        division_1_name: "Antioquia",
        division_2_code: "05607",
        division_2_name: "Retiro",
        parent_division_1_code: "05",
        latitude: 6.0617,
        longitude: -75.5028,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      // Suroeste
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "05",
        division_1_name: "Antioquia",
        division_2_code: "05038",
        division_2_name: "Andes",
        parent_division_1_code: "05",
        latitude: 5.6581,
        longitude: -75.8789,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "05",
        division_1_name: "Antioquia",
        division_2_code: "05042",
        division_2_name: "Angelópolis",
        parent_division_1_code: "05",
        latitude: 6.0958,
        longitude: -75.7139,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "05",
        division_1_name: "Antioquia",
        division_2_code: "05086",
        division_2_name: "Betania",
        parent_division_1_code: "05",
        latitude: 6.0903,
        longitude: -75.9811,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "05",
        division_1_name: "Antioquia",
        division_2_code: "05197",
        division_2_name: "Ciudad Bolívar",
        parent_division_1_code: "05",
        latitude: 5.8667,
        longitude: -76.0167,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "05",
        division_1_name: "Antioquia",
        division_2_code: "05234",
        division_2_name: "Fredonia",
        parent_division_1_code: "05",
        latitude: 5.9244,
        longitude: -75.6692,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "05",
        division_1_name: "Antioquia",
        division_2_code: "05541",
        division_2_name: "Jericó",
        parent_division_1_code: "05",
        latitude: 5.7947,
        longitude: -75.7869,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      // Urabá
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "05",
        division_1_name: "Antioquia",
        division_2_code: "05837",
        division_2_name: "Turbo",
        parent_division_1_code: "05",
        latitude: 8.0928,
        longitude: -76.7269,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "05",
        division_1_name: "Antioquia",
        division_2_code: "05034",
        division_2_name: "Apartadó",
        parent_division_1_code: "05",
        latitude: 7.8833,
        longitude: -76.6333,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "05",
        division_1_name: "Antioquia",
        division_2_code: "05147",
        division_2_name: "Carepa",
        parent_division_1_code: "05",
        latitude: 7.7586,
        longitude: -76.6508,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "05",
        division_1_name: "Antioquia",
        division_2_code: "05190",
        division_2_name: "Chigorodó",
        parent_division_1_code: "05",
        latitude: 7.6667,
        longitude: -76.6833,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "05",
        division_1_name: "Antioquia",
        division_2_code: "05490",
        division_2_name: "Necoclí",
        parent_division_1_code: "05",
        latitude: 8.4167,
        longitude: -76.7833,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "05",
        division_1_name: "Antioquia",
        division_2_code: "05045",
        division_2_name: "Arboletes",
        parent_division_1_code: "05",
        latitude: 8.8597,
        longitude: -76.4231,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      // Norte
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "05",
        division_1_name: "Antioquia",
        division_2_code: "05895",
        division_2_name: "Yarumal",
        parent_division_1_code: "05",
        latitude: 6.9650,
        longitude: -75.4178,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "05",
        division_1_name: "Antioquia",
        division_2_code: "05664",
        division_2_name: "Santa Rosa de Osos",
        parent_division_1_code: "05",
        latitude: 6.6453,
        longitude: -75.4611,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "05",
        division_1_name: "Antioquia",
        division_2_code: "05208",
        division_2_name: "Donmatías",
        parent_division_1_code: "05",
        latitude: 6.4642,
        longitude: -75.3894,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "05",
        division_1_name: "Antioquia",
        division_2_code: "05212",
        division_2_name: "Entrerríos",
        parent_division_1_code: "05",
        latitude: 6.5586,
        longitude: -75.5194,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      // Bajo Cauca
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "05",
        division_1_name: "Antioquia",
        division_2_code: "05142",
        division_2_name: "Caucasia",
        parent_division_1_code: "05",
        latitude: 7.9867,
        longitude: -75.1939,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "05",
        division_1_name: "Antioquia",
        division_2_code: "05495",
        division_2_name: "Nechí",
        parent_division_1_code: "05",
        latitude: 8.0956,
        longitude: -74.7769,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "05",
        division_1_name: "Antioquia",
        division_2_code: "05893",
        division_2_name: "Zaragoza",
        parent_division_1_code: "05",
        latitude: 7.4861,
        longitude: -74.8658,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "05",
        division_1_name: "Antioquia",
        division_2_code: "05579",
        division_2_name: "El Bagre",
        parent_division_1_code: "05",
        latitude: 7.5975,
        longitude: -74.8083,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      // Magdalena Medio
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "05",
        division_1_name: "Antioquia",
        division_2_code: "05585",
        division_2_name: "Puerto Berrío",
        parent_division_1_code: "05",
        latitude: 6.4889,
        longitude: -74.4028,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "05",
        division_1_name: "Antioquia",
        division_2_code: "05591",
        division_2_name: "Puerto Nare",
        parent_division_1_code: "05",
        latitude: 6.1919,
        longitude: -74.5828,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "05",
        division_1_name: "Antioquia",
        division_2_code: "05893",
        division_2_name: "Puerto Triunfo",
        parent_division_1_code: "05",
        latitude: 5.8706,
        longitude: -74.6414,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      // Occidente
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "05",
        division_1_name: "Antioquia",
        division_2_code: "05656",
        division_2_name: "Santa Fe de Antioquia",
        parent_division_1_code: "05",
        latitude: 6.5564,
        longitude: -75.8283,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "05",
        division_1_name: "Antioquia",
        division_2_code: "05313",
        division_2_name: "Sopetrán",
        parent_division_1_code: "05",
        latitude: 6.5011,
        longitude: -75.7453,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "05",
        division_1_name: "Antioquia",
        division_2_code: "05284",
        division_2_name: "San Jerónimo",
        parent_division_1_code: "05",
        latitude: 6.4394,
        longitude: -75.7289,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },

      // CUNDINAMARCA - PRINCIPALES MUNICIPIOS (116 total)
      // Sabana Centro
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25175",
        division_2_name: "Chía",
        parent_division_1_code: "25",
        latitude: 4.8619,
        longitude: -74.0517,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25899",
        division_2_name: "Zipaquirá",
        parent_division_1_code: "25",
        latitude: 5.0219,
        longitude: -74.0039,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25486",
        division_2_name: "Mosquera",
        parent_division_1_code: "25",
        latitude: 4.7061,
        longitude: -74.2325,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25214",
        division_2_name: "Cajicá",
        parent_division_1_code: "25",
        latitude: 4.9186,
        longitude: -74.0289,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25269",
        division_2_name: "Facatativá",
        parent_division_1_code: "25",
        latitude: 4.8139,
        longitude: -74.3547,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25295",
        division_2_name: "Funza",
        parent_division_1_code: "25",
        latitude: 4.7161,
        longitude: -74.2111,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25596",
        division_2_name: "Madrid",
        parent_division_1_code: "25",
        latitude: 4.7306,
        longitude: -74.2633,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25758",
        division_2_name: "Soacha",
        parent_division_1_code: "25",
        latitude: 4.5794,
        longitude: -74.2169,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25843",
        division_2_name: "Tocancipá",
        parent_division_1_code: "25",
        latitude: 4.9653,
        longitude: -73.9114,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25245",
        division_2_name: "Cota",
        parent_division_1_code: "25",
        latitude: 4.8089,
        longitude: -74.1036,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25754",
        division_2_name: "Sibaté",
        parent_division_1_code: "25",
        latitude: 4.4894,
        longitude: -74.2589,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25807",
        division_2_name: "Tabio",
        parent_division_1_code: "25",
        latitude: 4.9211,
        longitude: -74.0956,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25817",
        division_2_name: "Tenjo",
        parent_division_1_code: "25",
        latitude: 4.8711,
        longitude: -74.1464,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25785",
        division_2_name: "Sopó",
        parent_division_1_code: "25",
        latitude: 4.9094,
        longitude: -73.9428,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      // Sumapaz
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25290",
        division_2_name: "Fusagasugá",
        parent_division_1_code: "25",
        latitude: 4.3379,
        longitude: -74.3636,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25260",
        division_2_name: "Girardot",
        parent_division_1_code: "25",
        latitude: 4.3011,
        longitude: -74.8031,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25645",
        division_2_name: "Silvania",
        parent_division_1_code: "25",
        latitude: 4.4019,
        longitude: -74.3867,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25386",
        division_2_name: "Granada",
        parent_division_1_code: "25",
        latitude: 4.5294,
        longitude: -74.3711,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      // Oriente
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25394",
        division_2_name: "La Calera",
        parent_division_1_code: "25",
        latitude: 4.7219,
        longitude: -73.9681,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25126",
        division_2_name: "Choachí",
        parent_division_1_code: "25",
        latitude: 4.5286,
        longitude: -73.9225,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "25",
        division_1_name: "Cundinamarca",
        division_2_code: "25335",
        division_2_name: "Guasca",
        parent_division_1_code: "25",
        latitude: 4.8656,
        longitude: -73.8744,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },

      // VALLE DEL CAUCA - PRINCIPALES MUNICIPIOS (42 total)
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "76",
        division_1_name: "Valle del Cauca",
        division_2_code: "76001",
        division_2_name: "Cali",
        parent_division_1_code: "76",
        latitude: 3.4516,
        longitude: -76.5320,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "76",
        division_1_name: "Valle del Cauca",
        division_2_code: "76111",
        division_2_name: "Buenaventura",
        parent_division_1_code: "76",
        latitude: 3.8801,
        longitude: -77.0310,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "76",
        division_1_name: "Valle del Cauca",
        division_2_code: "76520",
        division_2_name: "Palmira",
        parent_division_1_code: "76",
        latitude: 3.5394,
        longitude: -76.3036,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "76",
        division_1_name: "Valle del Cauca",
        division_2_code: "76834",
        division_2_name: "Tuluá",
        parent_division_1_code: "76",
        latitude: 4.0850,
        longitude: -76.1950,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "76",
        division_1_name: "Valle del Cauca",
        division_2_code: "76147",
        division_2_name: "Cartago",
        parent_division_1_code: "76",
        latitude: 4.7467,
        longitude: -75.9117,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "76",
        division_1_name: "Valle del Cauca",
        division_2_code: "76113",
        division_2_name: "Buga",
        parent_division_1_code: "76",
        latitude: 3.9006,
        longitude: -76.2978,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "76",
        division_1_name: "Valle del Cauca",
        division_2_code: "76892",
        division_2_name: "Yumbo",
        parent_division_1_code: "76",
        latitude: 3.5833,
        longitude: -76.5000,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "76",
        division_1_name: "Valle del Cauca",
        division_2_code: "76275",
        division_2_name: "Florida",
        parent_division_1_code: "76",
        latitude: 3.3236,
        longitude: -76.2361,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "76",
        division_1_name: "Valle del Cauca",
        division_2_code: "76400",
        division_2_name: "Jamundí",
        parent_division_1_code: "76",
        latitude: 3.2636,
        longitude: -76.5369,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "76",
        division_1_name: "Valle del Cauca",
        division_2_code: "76606",
        division_2_name: "Roldanillo",
        parent_division_1_code: "76",
        latitude: 4.4133,
        longitude: -76.1519,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },

      // ATLÁNTICO - PRINCIPALES MUNICIPIOS (23 total)
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "08",
        division_1_name: "Atlántico",
        division_2_code: "08001",
        division_2_name: "Barranquilla",
        parent_division_1_code: "08",
        latitude: 10.9685,
        longitude: -74.7813,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "08",
        division_1_name: "Atlántico",
        division_2_code: "08758",
        division_2_name: "Soledad",
        parent_division_1_code: "08",
        latitude: 10.9183,
        longitude: -74.7686,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "08",
        division_1_name: "Atlántico",
        division_2_code: "08433",
        division_2_name: "Malambo",
        parent_division_1_code: "08",
        latitude: 10.8594,
        longitude: -74.7739,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "08",
        division_1_name: "Atlántico",
        division_2_code: "08141",
        division_2_name: "Sabanalarga",
        parent_division_1_code: "08",
        latitude: 10.6339,
        longitude: -74.9211,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "08",
        division_1_name: "Atlántico",
        division_2_code: "08078",
        division_2_name: "Baranoa",
        parent_division_1_code: "08",
        latitude: 10.7942,
        longitude: -74.9164,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "08",
        division_1_name: "Atlántico",
        division_2_code: "08606",
        division_2_name: "Puerto Colombia",
        parent_division_1_code: "08",
        latitude: 10.9875,
        longitude: -74.9547,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },

      // BOLÍVAR - PRINCIPALES MUNICIPIOS (45 total)
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "13",
        division_1_name: "Bolívar",
        division_2_code: "13001",
        division_2_name: "Cartagena de Indias",
        parent_division_1_code: "13",
        latitude: 10.3910,
        longitude: -75.4794,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "13",
        division_1_name: "Bolívar",
        division_2_code: "13430",
        division_2_name: "Magangué",
        parent_division_1_code: "13",
        latitude: 9.2414,
        longitude: -74.7547,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "13",
        division_1_name: "Bolívar",
        division_2_code: "13244",
        division_2_name: "El Carmen de Bolívar",
        parent_division_1_code: "13",
        latitude: 9.7172,
        longitude: -75.1211,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "13",
        division_1_name: "Bolívar",
        division_2_code: "13490",
        division_2_name: "Mompox",
        parent_division_1_code: "13",
        latitude: 9.2378,
        longitude: -74.4278,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "13",
        division_1_name: "Bolívar",
        division_2_code: "13654",
        division_2_name: "Turbaco",
        parent_division_1_code: "13",
        latitude: 10.3386,
        longitude: -75.4247,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },

      // SANTANDER - PRINCIPALES MUNICIPIOS (87 total)
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "68",
        division_1_name: "Santander",
        division_2_code: "68001",
        division_2_name: "Bucaramanga",
        parent_division_1_code: "68",
        latitude: 7.1254,
        longitude: -73.1198,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "68",
        division_1_name: "Santander",
        division_2_code: "68276",
        division_2_name: "Floridablanca",
        parent_division_1_code: "68",
        latitude: 7.0639,
        longitude: -73.0864,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "68",
        division_1_name: "Santander",
        division_2_code: "68547",
        division_2_name: "Piedecuesta",
        parent_division_1_code: "68",
        latitude: 6.9833,
        longitude: -73.0500,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "68",
        division_1_name: "Santander",
        division_2_code: "68689",
        division_2_name: "Girón",
        parent_division_1_code: "68",
        latitude: 7.0661,
        longitude: -73.1694,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "68",
        division_1_name: "Santander",
        division_2_code: "68081",
        division_2_name: "Barrancabermeja",
        parent_division_1_code: "68",
        latitude: 7.0653,
        longitude: -73.8547,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "68",
        division_1_name: "Santander",
        division_2_code: "68679",
        division_2_name: "San Gil",
        parent_division_1_code: "68",
        latitude: 6.5575,
        longitude: -73.1333,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "68",
        division_1_name: "Santander",
        division_2_code: "68755",
        division_2_name: "Socorro",
        parent_division_1_code: "68",
        latitude: 6.4697,
        longitude: -73.2597,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },

      // CALDAS - PRINCIPALES MUNICIPIOS (27 total)
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "17",
        division_1_name: "Caldas",
        division_2_code: "17001",
        division_2_name: "Manizales",
        parent_division_1_code: "17",
        latitude: 5.0689,
        longitude: -75.5174,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "17",
        division_1_name: "Caldas",
        division_2_code: "17380",
        division_2_name: "La Dorada",
        parent_division_1_code: "17",
        latitude: 5.4508,
        longitude: -74.6658,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "17",
        division_1_name: "Caldas",
        division_2_code: "17174",
        division_2_name: "Chinchiná",
        parent_division_1_code: "17",
        latitude: 4.9833,
        longitude: -75.6039,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "17",
        division_1_name: "Caldas",
        division_2_code: "17513",
        division_2_name: "Palestina",
        parent_division_1_code: "17",
        latitude: 5.0569,
        longitude: -75.6467,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "17",
        division_1_name: "Caldas",
        division_2_code: "17653",
        division_2_name: "Riosucio",
        parent_division_1_code: "17",
        latitude: 5.4214,
        longitude: -75.7028,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },

      // QUINDÍO - TODOS LOS MUNICIPIOS (12 total)
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "63",
        division_1_name: "Quindío",
        division_2_code: "63001",
        division_2_name: "Armenia",
        parent_division_1_code: "63",
        latitude: 4.5339,
        longitude: -75.6811,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "63",
        division_1_name: "Quindío",
        division_2_code: "63111",
        division_2_name: "Calarcá",
        parent_division_1_code: "63",
        latitude: 4.5289,
        longitude: -75.6419,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "63",
        division_1_name: "Quindío",
        division_2_code: "63190",
        division_2_name: "Circasia",
        parent_division_1_code: "63",
        latitude: 4.6172,
        longitude: -75.6350,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "63",
        division_1_name: "Quindío",
        division_2_code: "63272",
        division_2_name: "Filandia",
        parent_division_1_code: "63",
        latitude: 4.6739,
        longitude: -75.6578,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "63",
        division_1_name: "Quindío",
        division_2_code: "63401",
        division_2_name: "La Tebaida",
        parent_division_1_code: "63",
        latitude: 4.4506,
        longitude: -75.7872,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "63",
        division_1_name: "Quindío",
        division_2_code: "63470",
        division_2_name: "Montenegro",
        parent_division_1_code: "63",
        latitude: 4.5619,
        longitude: -75.7511,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "63",
        division_1_name: "Quindío",
        division_2_code: "63548",
        division_2_name: "Quimbaya",
        parent_division_1_code: "63",
        latitude: 4.6203,
        longitude: -75.7639,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "63",
        division_1_name: "Quindío",
        division_2_code: "63690",
        division_2_name: "Salento",
        parent_division_1_code: "63",
        latitude: 4.6378,
        longitude: -75.5703,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },

      // RISARALDA - PRINCIPALES MUNICIPIOS (14 total)
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "66",
        division_1_name: "Risaralda",
        division_2_code: "66001",
        division_2_name: "Pereira",
        parent_division_1_code: "66",
        latitude: 4.8133,
        longitude: -75.6961,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "66",
        division_1_name: "Risaralda",
        division_2_code: "66170",
        division_2_name: "Dosquebradas",
        parent_division_1_code: "66",
        latitude: 4.8392,
        longitude: -75.6728,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "66",
        division_1_name: "Risaralda",
        division_2_code: "66682",
        division_2_name: "Santa Rosa de Cabal",
        parent_division_1_code: "66",
        latitude: 4.8689,
        longitude: -75.6206,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "66",
        division_1_name: "Risaralda",
        division_2_code: "66383",
        division_2_name: "La Virginia",
        parent_division_1_code: "66",
        latitude: 4.9011,
        longitude: -75.8839,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },

      // TOLIMA - PRINCIPALES MUNICIPIOS (47 total)
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "73",
        division_1_name: "Tolima",
        division_2_code: "73001",
        division_2_name: "Ibagué",
        parent_division_1_code: "73",
        latitude: 4.4389,
        longitude: -75.2322,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "73",
        division_1_name: "Tolima",
        division_2_code: "73268",
        division_2_name: "Espinal",
        parent_division_1_code: "73",
        latitude: 4.1489,
        longitude: -74.8836,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "73",
        division_1_name: "Tolima",
        division_2_code: "73461",
        division_2_name: "Melgar",
        parent_division_1_code: "73",
        latitude: 4.2042,
        longitude: -74.6403,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "73",
        division_1_name: "Tolima",
        division_2_code: "73043",
        division_2_name: "Chaparral",
        parent_division_1_code: "73",
        latitude: 3.7239,
        longitude: -75.4856,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
      {
        country_code: "CO",
        country_name: "Colombia",
        administrative_level: 2,
        division_1_code: "73",
        division_1_name: "Tolima",
        division_2_code: "73411",
        division_2_name: "Líbano",
        parent_division_1_code: "73",
        latitude: 4.9197,
        longitude: -75.0636,
        timezone: "America/Bogota",
        is_active: true,
        created_at: now,
      },
    ];

    // Insert all departments
    for (const dept of departments) {
      await ctx.db.insert("geographic_locations", dept);
    }

    // Insert all municipalities
    for (const muni of municipalities) {
      await ctx.db.insert("geographic_locations", muni);
    }

    return {
      message: "Geographic data seeded successfully",
      departments: departments.length,
      municipalities: municipalities.length,
      total: departments.length + municipalities.length,
    };
  },
});
