/**
 * Validation Schemas Index
 *
 * Central export point for all validation schemas
 */

// Phase 1 validations (from main validations.ts)
export {
  signupSchema,
  emailVerificationSchema,
  companySetupSchema,
  facilityBasicInfoSchema,
  facilityLocationSchema,
  facilityCompleteSchema,
  loginSchema,
  invitationAcceptSchema,
  checkPasswordRequirements,
  allPasswordRequirementsMet,
  type SignupFormValues,
  type EmailVerificationFormValues,
  type CompanySetupFormValues,
  type FacilityBasicInfoFormValues,
  type FacilityLocationFormValues,
  type FacilityCompleteFormValues,
  type LoginFormValues,
  type InvitationAcceptFormValues,
  type PasswordRequirement,
} from '../validations';

// Phase 2 - Area validations
export {
  areaTypeSchema,
  areaStatusSchema,
  environmentalSpecsSchema,
  capacityConfigurationSchema,
  createAreaSchema,
  updateAreaSchema,
  areaFilterSchema,
  type CreateAreaInput,
  type UpdateAreaInput,
  type AreaFilterInput,
  type AreaType,
  type AreaStatus,
  type EnvironmentalSpecs,
} from './area';

// Phase 2 - Cultivar validations
export {
  cannabisVarietyTypeSchema,
  coffeeVarietyTypeSchema,
  varietyTypeSchema,
  cultivarStatusSchema,
  growthDifficultySchema,
  cultivarCharacteristicsSchema,
  optimalConditionsSchema,
  originMetadataSchema,
  createCustomCultivarSchema,
  linkSystemCultivarSchema,
  updateCultivarSchema,
  cultivarFilterSchema,
  type CreateCustomCultivarInput,
  type LinkSystemCultivarInput,
  type UpdateCultivarInput,
  type CultivarFilterInput,
  type CultivarStatus,
  type CultivarCharacteristics,
  type OptimalConditions,
  type OriginMetadata,
} from './cultivar';

// Phase 2 - Supplier validations
export {
  businessTypeSchema,
  nitSchema as supplierNitSchema,
  colombianPhoneSchema as supplierPhoneSchema,
  productCategoriesSchema,
  cropSpecializationSchema,
  certificationSchema,
  licenseSchema,
  createSupplierSchema,
  updateSupplierSchema,
  supplierFilterSchema,
  approveSupplierSchema,
  formatNIT,
  formatColombianPhone,
  type CreateSupplierInput,
  type UpdateSupplierInput,
  type SupplierFilterInput,
  type ApproveSupplierInput,
  type SupplierCertification,
  type SupplierLicense,
  type BusinessType,
} from './supplier';

// Phase 2 - Inventory validations
export {
  productCategorySchema,
  productStatusSchema,
  lotStatusSchema,
  qualityGradeSchema,
  sourceTypeSchema,
  productMetadataSchema,
  storageConditionsSchema,
  createProductSchema,
  updateProductSchema,
  createInventoryItemSchema,
  updateInventoryItemSchema,
  adjustInventoryQuantitySchema,
  inventoryFilterSchema,
  transferInventorySchema,
  type CreateProductInput,
  type UpdateProductInput,
  type CreateInventoryItemInput,
  type UpdateInventoryItemInput,
  type AdjustInventoryQuantityInput,
  type InventoryFilterInput,
  type TransferInventoryInput,
  type ProductCategory,
  type ProductStatus,
  type LotStatus,
  type QualityGrade,
  type SourceType,
  type StorageConditions,
} from './inventory';

// Phase 2 - Invitation validations
export {
  invitationStatusSchema,
  createInvitationSchema,
  bulkInvitationSchema,
  resendInvitationSchema,
  cancelInvitationSchema,
  acceptInvitationSchema,
  rejectInvitationSchema,
  invitationFilterSchema,
  updateInvitationSchema,
  type CreateInvitationInput,
  type BulkInvitationInput,
  type ResendInvitationInput,
  type CancelInvitationInput,
  type AcceptInvitationInput,
  type RejectInvitationInput,
  type InvitationFilterInput,
  type UpdateInvitationInput,
  type InvitationStatus,
} from './invitation';

// Phase 2 - Settings validations
export {
  workdaySchema,
  facilitySettingsSchema,
  accountSettingsSchema,
  userProfileSettingsSchema,
  notificationPreferencesSchema,
  changePasswordSchema,
  alertThresholdSettingsSchema,
  type FacilitySettingsInput,
  type AccountSettingsInput,
  type UserProfileSettingsInput,
  type NotificationPreferencesInput,
  type ChangePasswordInput,
  type AlertThresholdSettingsInput,
  type Workday,
} from './settings';

// Validation helpers
export {
  formatNIT as helperFormatNIT,
  validateNITCheckDigit,
  formatColombianPhone as helperFormatColombianPhone,
  validateDANECode,
  emailSchema as helperEmailSchema,
  passwordSchema as helperPasswordSchema,
  colombianPhoneSchema as helperPhoneSchema,
  nitSchema as helperNitSchema,
  dateRangeSchema,
  paginationSchema,
  sortOrderSchema,
  gpsCoordinatesSchema,
  checkPasswordRequirements as helperCheckPasswordRequirements,
  calculatePasswordStrength,
  validateSKU,
  formatSKU,
  validateGTIN,
  validateCountryCode,
  validateTimezone,
  validateCurrencyCode,
  validateEmailDomain,
  sanitizeString,
  validateRange,
  isDateInPast,
  isDateInFuture,
  daysUntilDate,
  isExpiringSoon,
  isExpired,
  getZodErrorMessage,
  formatZodErrors,
  isValidNumber,
  isValidTimestamp,
  isNonEmptyString,
  isValidEmail,
  isValidURL,
} from './helpers';
